spring.application.name=server

spring.datasource.url=jdbc:mysql://202.194.14.120:3306/java_2_35?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=java_2_35
spring.datasource.password=JavaP235@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

security.jwt.secret-key=SGVsbG8gV29ybGQga2VzaGUtc2VydmVyIGp3dC1zZWNyZXQta2V5
security.jwt.refresh-secret-key=SGVsbG8gV29ybGQga2VzaGUtc2VydmVyIHJlZnJlc2gtc2VjcmV0LWtleQ==
security.jwt.expiration-time=1800000
security.jwt.refresh-expiration-time=7200000

# 监听所有网络接口，允许外部访问
server.address=0.0.0.0
# 保持默认端口（或根据需要修改）
server.port=8080
